color0 #181211
color1 #ffb4ab
color2 #ffb4ab
color3 #e7bdb8
color4 #e0c38c
color5 #ffb4ab
color6 #e7bdb8
color7 #ede0de
color8 #a08c8a
color9 #ffb4ab
color10 #ffb4ab
color11 #e7bdb8
color12 #e0c38c
color13 #ffb4ab
color14 #e7bdb8
color15 #ede0de

cursor                #ede0de
cursor_text_color     #181211
background            #181211
foreground            #ede0de
selection_foreground  #d8c2bf
selection_background  #534341
active_border_color   #ffb4ab
inactive_border_color #534341
url_color             #ffb4ab
