color0 #200f0d
color1 #ffb4ab
color2 #ffb4aa
color3 #ffb4aa
color4 #ffb95d
color5 #ffb4aa
color6 #ffb4aa
color7 #fddbd6
color8 #ae8882
color9 #ffb4ab
color10 #ffb4aa
color11 #ffb4aa
color12 #ffb95d
color13 #ffb4aa
color14 #ffb4aa
color15 #fddbd6

cursor                #fddbd6
cursor_text_color     #200f0d
background            #200f0d
foreground            #fddbd6
selection_foreground  #e7bdb7
selection_background  #5e3f3b
active_border_color   #ffb4aa
inactive_border_color #5e3f3b
url_color             #ffb4aa

active_tab_foreground   #690003
active_tab_background   #ffb4aa
inactive_tab_foreground #e7bdb7
inactive_tab_background #5e3f3b
cursor_trail_color      #e7bdb7
