color0 #181210
color1 #ffb4ab
color2 #ffb59c
color3 #e7bdb0
color4 #d6c68d
color5 #ffb59c
color6 #e7bdb0
color7 #ede0dc
color8 #a08d87
color9 #ffb4ab
color10 #ffb59c
color11 #e7bdb0
color12 #d6c68d
color13 #ffb59c
color14 #e7bdb0
color15 #ede0dc

cursor                #ede0dc
cursor_text_color     #181210
background            #181210
foreground            #ede0dc
selection_foreground  #d8c2bb
selection_background  #53433f
active_border_color   #ffb59c
inactive_border_color #53433f
url_color             #ffb59c
