color0 #141311
color1 #ffb4ab
color2 #d0c6a9
color3 #ccc6b8
color4 #bfcab5
color5 #d0c6a9
color6 #ccc6b8
color7 #e6e2de
color8 #959085
color9 #ffb4ab
color10 #d0c6a9
color11 #ccc6b8
color12 #bfcab5
color13 #d0c6a9
color14 #ccc6b8
color15 #e6e2de

cursor                #e6e2de
cursor_text_color     #141311
background            #141311
foreground            #e6e2de
selection_foreground  #ccc6ba
selection_background  #4a463d
active_border_color   #d0c6a9
inactive_border_color #4a463d
url_color             #d0c6a9

active_tab_foreground   #36301c
active_tab_background   #d0c6a9
inactive_tab_foreground #ccc6ba
inactive_tab_background #4a463d
cursor_trail_color      #ccc6ba
