color0 #17120f
color1 #ffb4ab
color2 #ffb77a
color3 #e3c0a5
color4 #c4cb97
color5 #ffb77a
color6 #e3c0a5
color7 #ece0da
color8 #9e8e82
color9 #ffb4ab
color10 #ffb77a
color11 #e3c0a5
color12 #c4cb97
color13 #ffb77a
color14 #e3c0a5
color15 #ece0da

cursor                #ece0da
cursor_text_color     #17120f
background            #17120f
foreground            #ece0da
selection_foreground  #d6c3b6
selection_background  #51443b
active_border_color   #ffb77a
inactive_border_color #51443b
url_color             #ffb77a
