color0 #fff8f6
color1 #ba1a1a
color2 #8a4f30
color3 #775748
color4 #5e6223
color5 #ffb691
color6 #e7beab
color7 #201a17
color8 #85736c
color9 #ba1a1a
color10 #8a4f30
color11 #775748
color12 #5e6223
color13 #ffb691
color14 #e7beab
color15 #201a17

cursor                #201a17
cursor_text_color     #fff8f6
background            #fff8f6
foreground            #201a17
selection_foreground  #52443d
selection_background  #f4ded4
active_border_color   #8a4f30
inactive_border_color #f4ded4
url_color             #8a4f30

active_tab_foreground   #ffffff
active_tab_background   #8a4f30
inactive_tab_foreground #52443d
inactive_tab_background #f4ded4
cursor_trail_color      #52443d
