foreground            #ece0dd
background            #171211
selection_foreground  #502415
selection_background  #fdb6a0
url_color             #96d2c8
cursor                #fdb6a0
cursor_text_color     #502415

color0   #171211
color1   #ffb4ab
color2   #fdb6a0
color3   #96d2c8
color4   #fdb6a0
color5   #96d2c8
color6   #39746c
color7   #ece0dd

color8   #9f8d87
color9   #ffb4ab
color10  #fdb6a0
color11  #96d2c8
color12  #fdb6a0
color13  #96d2c8
color14  #39746c
color15  #ece0dd

tab_bar_background              #171211
tab_bar_margin_color            #171211
active_tab_foreground           #502415
active_tab_background           #fdb6a0
inactive_tab_foreground         #d7c2bc
inactive_tab_background         #171211
