keep-open=yes
title=${path}
vo=gpu-next
gpu-api=vulkan
hwdec=vaapi
gpu-context=waylandvk
tone-mapping=bt.2390
hdr-compute-peak=yes
target-colorspace-hint=no
video-sync=display-resample
interpolation=yes
tscale=oversample 
