# Messages
set -g message-style "fg=#e6e2de,bg=default,bold"

# Pane borders
set-option -g pane-border-style "fg=#d0c6a9,bg=default"
set-option -g pane-active-border-style "fg=#bfcab5,bg=default"

# Status bar colors (transparent background)
set-option -g status-fg "#e6e2de"
set-option -g status-bg default
set-option -g status-style "fg=#e6e2de,bg=default"

# Selection mode
set-option -g mode-style "fg=#141311,bg=#d0c6a9"

# Formatting
set-option -g status-left-style none
set -g status-left-length 60
set -g status-left ''

set-option -g status-right-style none
set -g status-right-length 120
set -g status-right "#[fg=#655e47]#[fg=#141311,bg=#655e47] #[fg=#e6e2de,bg=default] #W #[fg=#655e47]#[fg=#141311,bg=#655e47] #[fg=#e6e2de,bg=default] #S "

set -g window-status-separator "#[bg=default] "
set -g window-status-current-format "#[fg=#e6e2de,bg=default] #W #[fg=#141311,bg=#d0c6a9] 󰈸#[fg=#d0c6a9,bg=default]"
set -g window-status-format "#[fg=#e6e2de,bg=default] #W #[fg=#141311,bg=#655e47] #I#[fg=#655e47,bg=default]"
