# Messages
set -g message-style "fg=#201a17,bg=default,bold"

# Pane borders
set-option -g pane-border-style "fg=#8a4f30,bg=default"
set-option -g pane-active-border-style "fg=#5e6223,bg=default"

# Status bar colors (transparent background)
set-option -g status-fg "#201a17"
set-option -g status-bg default
set-option -g status-style "fg=#201a17,bg=default"

# Selection mode
set-option -g mode-style "fg=#fff8f6,bg=#8a4f30"

# Formatting
set-option -g status-left-style none
set -g status-left-length 60
set -g status-left ''

set-option -g status-right-style none
set -g status-right-length 120
set -g status-right "#[fg=#ffb691]#[fg=#fff8f6,bg=#ffb691] #[fg=#201a17,bg=default] #W #[fg=#ffb691]#[fg=#fff8f6,bg=#ffb691] #[fg=#201a17,bg=default] #S "

set -g window-status-separator "#[bg=default] "
set -g window-status-current-format "#[fg=#201a17,bg=default] #W #[fg=#fff8f6,bg=#8a4f30] 󰈸#[fg=#8a4f30,bg=default]"
set -g window-status-format "#[fg=#201a17,bg=default] #W #[fg=#fff8f6,bg=#ffb691] #I#[fg=#ffb691,bg=default]"
