# Messages
set -g message-style "fg=#ece0da,bg=default,bold"

# Pane borders
set-option -g pane-border-style "fg=#ffb77a,bg=default"
set-option -g pane-active-border-style "fg=#c4cb97,bg=default"

# Status bar colors (transparent background)
set-option -g status-fg "#ece0da"
set-option -g status-bg default
set-option -g status-style "fg=#ece0da,bg=default"

# Selection mode
set-option -g mode-style "fg=#17120f,bg=#ffb77a"

# Formatting
set-option -g status-left-style none
set -g status-left-length 60
set -g status-left ''

set-option -g status-right-style none
set -g status-right-length 120
set -g status-right "#[fg=#8f4e00]#[fg=#17120f,bg=#8f4e00] #[fg=#ece0da,bg=default] #W #[fg=#8f4e00]#[fg=#17120f,bg=#8f4e00] #[fg=#ece0da,bg=default] #S "

set -g window-status-separator "#[bg=default] "
set -g window-status-current-format "#[fg=#ece0da,bg=default] #W #[fg=#17120f,bg=#ffb77a] 󰈸#[fg=#ffb77a,bg=default]"
set -g window-status-format "#[fg=#ece0da,bg=default] #W #[fg=#17120f,bg=#8f4e00] #I#[fg=#8f4e00,bg=default]"
