hl.exec_cmd("noctalia")
hl.exec_cmd("dbus-update-activation-environment --all")
hl.exec_cmd("sleep 1 & dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
hl.exec_cmd("easyeffects --hide-window --service-mode")
hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
