[bar.main]
thickness = 25
border_width = 0.3
capsule = true
radius = 0
margin_edge = 0
position = "top"
margin_ends = 0
start = ["control-center", "workspaces", "active_window"]
center = ["media"]
end = ["tray", "ram", "clock-12h"]
background_opacity = 1.00
capsule_opacity = 1.00
